storage:
  pg_user: testuser
  pg_password: secret
  pg_database: db
  container_name: db
server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s
jwt:
  issuer: auth-svc
  secret: secret
  token_ttl: 5m
  session_ttl: 1h
  refresh_token_length: 32
